### ISSUE TITLE
ERROR  when run “npm start”

### ISSUE THREAD

**Issue by ShengtianM** [vega/voyager#235]
When I run ‘npm start’, it goes wrong. In browse, I cann't select data fields in data selector pannel.
My nodejs version is v4.2.3-linux-x64
The Log is that:
 START:
  Service: Fields
    ✔ should test something
  Service: Visrec
    ✔ should do something
  Directive: encodingVariations
    ✔ should make hidden element visible
  Directive: fieldList
    ✖ should make hidden element visible
  Directive: fieldListItem
    ✖ should make hidden element visible
  Directive: functionList
    ✔ should have correct number of radio
LOG: '[Logging] ', 'FIELDS_CHANGE', '', Object{selected: [], list: []}
  Directive: visList
    ✖ should add vis list element

Finished in 0.37 secs / 0.276 secs

FAILED TESTS:
  Directive: fieldList
    ✖ should make hidden element visible
      PhantomJS 1.9.8 (Linux 0.0.0)
    TypeError: 'undefined' is not an object (evaluating 'scope.field.name')
        at /home/ec2-user/voyager/bower_components/vega-lite-ui/vlui.js:1818
        at /home/ec2-user/voyager/bower_components/angular/angular.js:8835
        at invokeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8841)
        at nodeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8340)
        at delayedNodeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8590)
        at compositeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:7731)
        at nodeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8330)
        at delayedNodeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8590)
        at compositeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:7731)
        at compositeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:7734)
        at publicLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:7611)
        at /home/ec2-user/voyager/bower_components/angular/angular.js:7752
        at controllersBoundTransclude (/home/ec2-user/voyager/bower_components/angular/angular.js:8362)
        at ngRepeatAction (/home/ec2-user/voyager/bower_components/angular/angular.js:27583)
        at $watchCollectionAction (/home/ec2-user/voyager/bower_components/angular/angular.js:15761)
        at /home/ec2-user/voyager/bower_components/angular/angular.js:15896
        at /home/ec2-user/voyager/src/components/fieldlist/fieldlist.test.js:48

Directive: fieldListItem
    ✖ should make hidden element visible
      PhantomJS 1.9.8 (Linux 0.0.0)
    TypeError: 'undefined' is not an object (evaluating 'scope.field.name')
        at /home/ec2-user/voyager/bower_components/vega-lite-ui/vlui.js:1818
        at /home/ec2-user/voyager/bower_components/angular/angular.js:8835
        at invokeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8841)
        at nodeLinkFn (/home/ec2-user/voyager/bower_components/angular/angular.js:8340)
        at /home/ec2-user/voyager/bower_components/angular/angular.js:8573
        at processQueue (/home/ec2-user/voyager/bower_components/angular/angular.js:14792)
        at /home/ec2-user/voyager/bower_components/angular/angular.js:14808
        at /home/ec2-user/voyager/bower_components/angular/angular.js:16052
        at /home/ec2-user/voyager/bower_components/angular/angular.js:15870
        at /home/ec2-user/voyager/src/components/fieldlistitem/fieldlistitem.test.js:35

 Directive: visList
    ✖ should add vis list element
      PhantomJS 1.9.8 (Linux 0.0.0)
    TypeError: 'undefined' is not a function (evaluating 'vl.shorthand.shortenFieldDefs(selectedFields)')
        at /home/ec2-user/voyager/src/app/visrec/visrec.service.js:124
        at updateFields (/home/ec2-user/voyager/src/components/vislist/vislist.js:55)
        at /home/ec2-user/voyager/src/components/vislist/vislist.js:66
        at /home/ec2-user/voyager/bower_components/angular/angular.js:15896
        at /home/ec2-user/voyager/src/components/vislist/vislist.test.js:24

**Comment by thathert** [comment]
+1 -- I'm also running into this

**Comment by domoritz** [comment]
Thank you for reporting the issue. We'll look into these. I suspect that the errors you see on the command line are only test failures and may be unrelated to the problems in the UI.

**Comment by thathert** [comment]
Thanks for the quick reply @domoritz. To give some more context on what I'm running into: 

node: v0.12.0
npm: 2.5.1

I have pulled a fresh copy of master and run `npm install`. `node_modules` and `bower_components` seem to be fetched fine. I'm prompted to pick a version of `vega-lite`, so I go with the newer (`0.9.2`).

    Unable to find a suitable version for vega-lite, please choose one:
        1) vega-lite#^0.8.2 which resolved to 0.8.3 and is required by vega-lite-ui#0.8.1
        2) vega-lite#^0.9.0 which resolved to 0.9.2 and is required by viscompass#0.6.2

Tests fail like in @ShengtianM's comment above, and then when I go to localhost:3000 I get some logs and then an error:

    [Logging]  DATASET_CHANGE Cars undefined
    [Logging]  BOOKMARK_OPEN undefined undefined
    [Logging]  FIELDS_CHANGE  Object
        list: Array[0]
        selected: Array[0]
    gen time – projections    : 1 aggregates: 0 encodings:0 total: 1
    TypeError: vl.data.stats is not a function
        at Object.Dataset.updateFromData (vlui.js:1491)
        at vlui.js:1471
        at processQueue (angular.js:14792)
        at angular.js:14808
        at Scope.$eval (angular.js:16052)
        at Scope.$digest (angular.js:15870)
        at Scope.$apply (angular.js:16160)
        at done (angular.js:10589)
        at completeRequest (angular.js:10787)
        at XMLHttpRequest.requestLoaded (angular.js:10728)

HTH -- let me know if there's anything else that could help

**Comment by domoritz** [comment]
There has been a lot of churn in vega-lite recently as we are approaching a 1.0 release very soon. We will update vega-lite-ui, polestar and voyager accordingly. I haven't tried it but I think vl0.8.3 should work. 

The deployed version on https://github.com/vega/voyager/tree/gh-pages should work fine but of course cannot be changed easily. 

Great that you are using voyager @ShengtianM and @thathert! Just out of curiosity, what are you using it for?

**Comment by thathert** [comment]
I have a background in UI, data vis, and analytics. After seeing the vega suite at OpenVisConf last year my teammates and I have been interested in the tools and how we can apply them for data exploration and visualization (contrasting with other tools like Tableau.)

Looks like swapping to vl0.8.3 is running into some separate issues :confused: 

    TypeError: vl.shorthand.shortenFieldDefs is not a function
        at Object.Visrec.update.projections (visrec.service.js:124)
        at updateFields (vislist.js:55)
        at Object.fn (vislist.js:66)
        at Scope.$digest (angular.js:15896)
        at Scope.$apply (angular.js:16160)
        at done (angular.js:10589)
        at completeRequest (angular.js:10787)
        at XMLHttpRequest.requestLoaded (angular.js:10728)

    TypeError: Cannot read property 'ORDINAL' of undefined
        at resetField (fields.js:15)
        at fields.js:25
        at arrayReduce (lodash.js:1450)
        at Function.<anonymous> (lodash.js:3445)
        at LodashWrapper.reduce (lodash.js:11370)
        at Fields.updateSchema (fields.js:24)
        at processQueue (angular.js:14792)
        at angular.js:14808
        at Scope.$eval (angular.js:16052)
        at Scope.$digest (angular.js:15870)

    TypeError: Cannot read property 'name' of undefined
        at link (http://localhost:3003/bower_components/vega-lite-ui/vlui.js:1818:48)
        at http://localhost:3003/bower_components/angular/angular.js:8835:44
        at invokeLinkFn (http://localhost:3003/bower_components/angular/angular.js:8841:9)
        at nodeLinkFn (http://localhost:3003/bower_components/angular/angular.js:8335:11)
        at http://localhost:3003/bower_components/angular/angular.js:8572:13
        at processQueue (http://localhost:3003/bower_components/angular/angular.js:14792:28)
        at http://localhost:3003/bower_components/angular/angular.js:14808:27
        at Scope.$eval (http://localhost:3003/bower_components/angular/angular.js:16052:28)
        at Scope.$digest (http://localhost:3003/bower_components/angular/angular.js:15870:31)
        at Scope.$apply (http://localhost:3003/bower_components/angular/angular.js:16160:24) <span class="flex-grow-1 list-item clickable field-info ng-isolate-scope" field-def="fieldDef" show-type="true" show-caret="true" disable-count-caret="true" show-info="true" popup-content="popupContent" action="Fields.toggleSelected(fieldDef.field)" ng-class="{selected: Fields.isSelected(fieldDef.field), excluded: Fields.isSelected(fieldDef.field)===false, highlighted: Fields.highlighted[fieldDef.field]}">

We can use the version that you have linked to in your response and I'll keep an eye on progress as vega-lite version 1.0 is approached. Thanks again, excited to see what's in the future of these projects.

**Comment by ShengtianM** [comment]
Our team want to develop a BI platform, we want to apply voyager for data exploration and visualization
part of BI platform.

It has some progress in this ERROR. It can go well as http://vega.github.io/voyager/ .
cd voyager
gulp build
then it will build a folder named "dist".
I had download the js file (app.js vendor.js) from the http://vega.github.io/voyager/ , and I copy them to the "dist/scripts/", then click "dist/index.html", it will run like http://vega.github.io/voyager/

**Comment by kanitw** [comment]
Fixed in current master.
