### ISSUE TITLE
`src/reducers/index.test.ts` fail to run on Travis

### ISSUE THREAD

**Issue by kanitw** [vega/voyager#686]
![image](https://user-images.githubusercontent.com/111269/29989967-983e66ce-8f2b-11e7-8d91-0c29f2c7838a.png)
```
  ● Test suite failed to run
    ProcessTerminatedError: cancel after 2 retries!
      
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:75:36)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
A worker process has quit unexpectedly! Most likely this is an initialization error.
pec in JSON and, if applicable, screenshots or GIF videos (e.g., using https://www.cockos.com/licecap/)
```

**Comment by ZeningQu** [comment]
Had the same issue today with `actions/index.test.ts`

![screen shot 2018-02-13 at 3 11 11 pm](https://user-images.githubusercontent.com/822034/36179190-2fe2c346-10d0-11e8-95d8-7ff8fd822412.png)

```
FAIL  src/actions/index.test.ts
  ● Test suite failed to run
    ProcessTerminatedError: cancel after 2 retries!
      
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:75:36)
      at ontimeout (timers.js:386:11)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
A worker process has quit unexpectedly! Most likely this is an initialization error.
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.13.0/bin/node" "/home/travis/.nvm/versions/node/v6.13.0/bin/npm" "run" "codecov"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! datavoyager@2.0.0-alpha.15 codecov: `jest --no-cache --coverage && codecov`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the datavoyager@2.0.0-alpha.15 codecov script 'jest --no-cache --coverage && codecov'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the datavoyager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --no-cache --coverage && codecov
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs datavoyager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls datavoyager
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/vega/voyager/npm-debug.log
The command "npm run codecov" exited with 1.
```
